@echo off
setlocal

cd /d "%~dp0"

set "TASK=assembleDebug"
if /I "%~1"=="release" set "TASK=assembleRelease"
if /I "%~1"=="debug" set "TASK=assembleDebug"
set "SDK_DIR="

if defined JAVA_HOME (
    if exist "%JAVA_HOME%\java.exe" (
        for %%I in ("%JAVA_HOME%\..") do set "JAVA_HOME=%%~fI"
    )
)

if defined JAVA_HOME (
    if not exist "%JAVA_HOME%\bin\java.exe" (
        set "JAVA_HOME="
    )
)

if not defined JAVA_HOME (
    if exist "F:\Code\Env\JDK21\bin\java.exe" (
        set "JAVA_HOME=F:\Code\Env\JDK21"
    ) else if exist "F:\Code\Env\JDK25\bin\java.exe" (
        set "JAVA_HOME=F:\Code\Env\JDK25"
    )
)

if not defined JAVA_HOME (
    echo JAVA_HOME is not configured and no fallback JDK was found.
    exit /b 1
)

if defined ANDROID_HOME (
    if exist "%ANDROID_HOME%\platform-tools\adb.exe" (
        set "SDK_DIR=%ANDROID_HOME%"
    )
)

if not defined SDK_DIR (
    if defined ANDROID_SDK_ROOT (
        if exist "%ANDROID_SDK_ROOT%\platform-tools\adb.exe" (
            set "SDK_DIR=%ANDROID_SDK_ROOT%"
        )
    )
)

if not defined SDK_DIR (
    if exist "F:\Code\Env\AndroidSdk_User\Sdk\platform-tools\adb.exe" (
        set "SDK_DIR=F:\Code\Env\AndroidSdk_User\Sdk"
    ) else if exist "F:\Code\Env\AndroidSDK\platform-tools\adb.exe" (
        set "SDK_DIR=F:\Code\Env\AndroidSDK"
    )
)

if not defined SDK_DIR (
    echo Android SDK was not found.
    echo Please set ANDROID_HOME or ANDROID_SDK_ROOT, or install the SDK locally.
    exit /b 1
)

for %%I in ("%SDK_DIR%") do set "SDK_DIR=%%~fI"
set "ANDROID_HOME=%SDK_DIR%"
set "ANDROID_SDK_ROOT=%SDK_DIR%"
set "SDK_DIR_PROP=%SDK_DIR:\=/%"

(
    echo ## This file is auto-generated by build.bat
    echo sdk.dir=%SDK_DIR_PROP%
) > "%~dp0local.properties"

if not defined GRADLE_USER_HOME (
    set "GRADLE_USER_HOME=%CD%\.gradle-user"
)

echo Using JAVA_HOME=%JAVA_HOME%
echo Using ANDROID_HOME=%ANDROID_HOME%
echo Building with %TASK%...
call "%~dp0gradlew.bat" --no-daemon %TASK%
if errorlevel 1 (
    echo Build failed.
    exit /b %errorlevel%
)

if /I "%TASK%"=="assembleRelease" (
    echo APK: %CD%\app\build\outputs\apk\release\app-release.apk
) else (
    echo APK: %CD%\app\build\outputs\apk\debug\app-debug.apk
)

endlocal
